[{"Vulnerability": {"Severity": "High", "NamespaceName": "centos:7", "FixedIn": [{"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-abi-whitelists"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-bootwrapper"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-tools"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-tools-libs-devel"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "perf"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "python-perf"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-devel"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-headers"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-tools-libs"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-debug"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-doc"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-kdump-devel"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-debug-devel"}, {"VersionFormat": "rpm", "NamespaceName": "centos:7", "Version": "0:3.10.0-693.1.1.el7", "Name": "kernel-kdump"}], "Link": "https://access.redhat.com/errata/RHSA-2017:2473", "Description": "The kernel packages contain the Linux kernel, the core of any Linux operating system. Security Fix(es): * A race condition was found in the Linux kernel, present since v3.14-rc1 through v4.12. The race happens between threads of inotify_handle_event() and vfs_rename() while running the rename operation against the same file. As a result of the race the next slab data or the slab's free list pointer can be corrupted with attacker-controlled data. (CVE-2017-7533, Important) Red Hat would like to thank Leilei Lin (Alibaba Group), Fan Wu (The University of Hong Kong), and Shixiong Zhao (The University of Hong Kong) for reporting this issue. Bug Fix(es): * Previously, direct I/O read operations going past EOF returned an invalid error number, instead of reading 0 bytes and returning success, if these operations were in same XFS block with EOF. Consequently, creating multiple VMs from a Red Hat Enterprise Linux 7.4 template caused all the VMs to become unresponsive in the 'Image Locked' state. This update fixes the direct I/O feature of the file system, and VMs created from a Red Hat Enterprise Linux 7.4 template now work as expected. (BZ#1475669)", "Name": "RHSA-2017:2473"}}]